import type { D1Database } from './types';
import type { ContactInput, LeadInput, LeadStatus, OrganizationInput } from './validation';

export interface Organization { id: string; name: string; slug?: string; createdAt: string; updatedAt: string; }
export interface Contact extends ContactInput { id: string; organizationId: string; createdAt: string; updatedAt: string; }
export interface Lead extends LeadInput { id: string; workspaceId: string; createdAt: string; updatedAt: string; }
export interface CrmRepository { organizations(limit: number, offset: number): Promise<Organization[]>; organization(id: string): Promise<Organization | null>; createOrganization(id: string, input: OrganizationInput, now: string): Promise<Organization>; contacts(orgId: string, limit: number, offset: number): Promise<Contact[]>; contact(orgId: string, id: string): Promise<Contact | null>; createContact(orgId: string, id: string, input: ContactInput, now: string): Promise<Contact>; updateContact(orgId: string, id: string, input: Partial<ContactInput>, now: string): Promise<Contact | null>; leads(orgId: string, limit: number, offset: number): Promise<Lead[]>; lead(orgId: string, id: string): Promise<Lead | null>; createLead(orgId: string, id: string, input: LeadInput, now: string): Promise<Lead>; updateLead(orgId: string, id: string, input: Partial<LeadInput>, now: string): Promise<Lead | null>; }

type Row = Record<string, unknown>;
export class D1CrmRepository implements CrmRepository {
  constructor(private readonly db: D1Database) { }
  async organizations(limit: number, offset: number) { return this.rows<OrganizationRow>('SELECT * FROM organizations ORDER BY created_at DESC LIMIT ?1 OFFSET ?2', limit, offset).then(rows => rows.map(org)); }
  async organization(id: string) { return this.db.prepare('SELECT * FROM organizations WHERE id = ?1 LIMIT 1').bind(id).first<OrganizationRow>().then(row => row ? org(row) : null); }
  async createOrganization(id: string, input: OrganizationInput, now: string) { await this.db.prepare('INSERT INTO organizations (id, name, slug, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?4)').bind(id, input.name, input.slug ?? null, now).run(); return (await this.organization(id)) as Organization; }
  async contacts(orgId: string, limit: number, offset: number) { return this.rows<ContactRow>('SELECT * FROM contacts WHERE organization_id = ?1 ORDER BY created_at DESC LIMIT ?2 OFFSET ?3', orgId, limit, offset).then(rows => rows.map(contact)); }
  async contact(orgId: string, id: string) { return this.db.prepare('SELECT * FROM contacts WHERE organization_id = ?1 AND id = ?2 LIMIT 1').bind(orgId, id).first<ContactRow>().then(row => row ? contact(row) : null); }
  async createContact(orgId: string, id: string, input: ContactInput, now: string) { await this.db.prepare('INSERT INTO contacts (id, organization_id, full_name, email, phone, title, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7)').bind(id, orgId, input.fullName, input.email ?? null, input.phone ?? null, input.title ?? null, now).run(); return (await this.contact(orgId, id)) as Contact; }
  async updateContact(orgId: string, id: string, input: Partial<ContactInput>, now: string) { const old = await this.contact(orgId, id); if (!old) return null; const next = { ...old, ...input }; await this.db.prepare('UPDATE contacts SET full_name = ?1, email = ?2, phone = ?3, title = ?4, updated_at = ?5 WHERE organization_id = ?6 AND id = ?7').bind(next.fullName, next.email ?? null, next.phone ?? null, next.title ?? null, now, orgId, id).run(); return this.contact(orgId, id); }
  async leads(orgId: string, limit: number, offset: number) { return this.rows<LeadRow>('SELECT * FROM crm_leads WHERE workspace_id = ?1 ORDER BY created_at DESC LIMIT ?2 OFFSET ?3', orgId, limit, offset).then(rows => rows.map(lead)); }
  async lead(orgId: string, id: string) { return this.db.prepare('SELECT * FROM crm_leads WHERE workspace_id = ?1 AND id = ?2 LIMIT 1').bind(orgId, id).first<LeadRow>().then(row => row ? lead(row) : null); }
  async createLead(orgId: string, id: string, input: LeadInput, now: string) { await this.db.prepare('INSERT INTO crm_leads (id, workspace_id, company_id, primary_contact_id, source_id, stage_id, owner_user_id, status, priority, score, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?11)').bind(id, orgId, input.companyId, input.primaryContactId, input.sourceId ?? null, input.stageId, input.ownerUserId ?? null, input.status, input.priority ?? null, input.score ?? null, now).run(); return (await this.lead(orgId, id)) as Lead; }
  async updateLead(orgId: string, id: string, input: Partial<LeadInput>, now: string) { const old = await this.lead(orgId, id); if (!old) return null; const next = { ...old, ...input }; await this.db.prepare('UPDATE crm_leads SET company_id = ?1, primary_contact_id = ?2, source_id = ?3, stage_id = ?4, owner_user_id = ?5, status = ?6, priority = ?7, score = ?8, updated_at = ?9 WHERE workspace_id = ?10 AND id = ?11').bind(next.companyId, next.primaryContactId, next.sourceId ?? null, next.stageId, next.ownerUserId ?? null, next.status, next.priority ?? null, next.score ?? null, now, orgId, id).run(); return this.lead(orgId, id); }
  private rows<T>(query: string, ...values: unknown[]) { return this.db.prepare(query).bind(...values).all<T>().then(result => result.results); }
}
type OrganizationRow = Row & { id: string; name: string; slug?: string | null; created_at: string; updated_at: string };
type ContactRow = Row & { id: string; organization_id: string; full_name: string; email?: string | null; phone?: string | null; title?: string | null; created_at: string; updated_at: string };
type LeadRow = Row & { id: string; workspace_id: string; company_id: string; primary_contact_id: string; source_id?: string | null; stage_id: string; owner_user_id?: string | null; status: LeadStatus; priority?: number | null; score?: number | null; created_at: string; updated_at: string };
const org = (r: OrganizationRow): Organization => ({ id: r.id, name: r.name, ...(r.slug ? { slug: r.slug } : {}), createdAt: r.created_at, updatedAt: r.updated_at });
const contact = (r: ContactRow): Contact => ({ id: r.id, organizationId: r.organization_id, fullName: r.full_name, ...(r.email ? { email: r.email } : {}), ...(r.phone ? { phone: r.phone } : {}), ...(r.title ? { title: r.title } : {}), createdAt: r.created_at, updatedAt: r.updated_at });
const lead = (r: LeadRow): Lead => ({ id: r.id, workspaceId: r.workspace_id, companyId: r.company_id, primaryContactId: r.primary_contact_id, ...(r.source_id ? { sourceId: r.source_id } : {}), stageId: r.stage_id, ...(r.owner_user_id ? { ownerUserId: r.owner_user_id } : {}), status: r.status, ...(r.priority !== null && r.priority !== undefined ? { priority: r.priority } : {}), ...(r.score !== null && r.score !== undefined ? { score: r.score } : {}), createdAt: r.created_at, updatedAt: r.updated_at });
